### ISSUE TITLE
Switch problems

### ISSUE THREAD

**Issue by Barbara1984** [theyosh/TerrariumPI#116]
Hello, why can not I add new switches?

**Comment by nopalpite** [comment]
I have the same issue with webcam

**Comment by theyosh** [comment]
@nopalpite that is a known issue and fixed in development. I just put this fix in the master branch. So for you just do a git pull and clear browser cache. That should fix you issue.

@Barbara1984 I have to look into this. I can add a new switch. What kind of values are you using, and what does the screen session show when you press save? Sounds like the server cannot store them somehow.

**Comment by nopalpite** [comment]
So, i've done a git pull and clear browser cache, but it still won't work .

**Comment by theyosh** [comment]
then I need more information. If the save option does not work, there should be information in the screen session. Else please describe what you are filling in and what is happening

**Comment by Barbara1984** [comment]
Hi, I use because pin 22 for a relay via GPIO reverse, if I click on save this green bar or the green message is not when I reload the page then the switch is not saved.

**Comment by theyosh** [comment]
@nopalpite try setting Rotation d'image to 0 degrees and save then. If that does not help try: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi Because it sounds like you are not allowed to read out the /dev/video0 device.

@Barbara1984 for you also: https://github.com/theyosh/TerrariumPI/wiki/FAQ#how-to-debug-terrariumpi . Because there should be an error when the save is not successful somehow.

**Comment by nopalpite** [comment]
Ok, settings  Rotation to 0 degrees fix it ! Thanks for your time.

**Comment by Barbara1984** [comment]
So with me unfortunately no error does not matter how often I press Save, he just does not save

**Comment by Barbara1984** [comment]
Currently I have 12 switches, but I do not think this makes my problem. Restart and cache does not help unfortunately. This is the named switch.

![unbenannt](https://user-images.githubusercontent.com/34924591/36948956-5641afea-1fe2-11e8-9b50-32ca0b2cf560.png)

**Comment by Barbara1984** [comment]
So .. I would like to add this switch, but can click save 10 times and nothing happens, if I should now delete a switch this is not possible for me because I can not press save

**Comment by Barbara1984** [comment]
Can I add a new switch via settings.cfg?

**Comment by Barbara1984** [comment]
Theyosh, are you still here :-)

**Comment by theyosh** [comment]
yes, but I do like my free time. 
And yes you can try to duplicate a switches part in the config. Make sure the ID parts is changed. But I do not know what then will happen when you start to edit the switches in the webinterface. Because the ID will be changed then according to the code.

Also I will slow down on answering posts.... I have a 40+ hour work week... this is hobby and should be a hobby.

**Comment by Barbara1984** [comment]
Ok thank you I will try it but unfortunately I can not add a new switch yet :-(

**Comment by Barbara1984** [comment]
So I've come to think that it can only be s.den settings.cfg because if I delete them from the PI, I can save switch again, if I load them again on the PI is not again.

**Comment by theyosh** [comment]
Could you upload the settings.cfg file that is not working? Maybe I can see what is wrong with it. Still this is a strange issue

**Comment by Barbara1984** [comment]
Yes clearly no topic, here the settings.cfg
[settings.zip](https://github.com/theyosh/TerrariumPI/files/1786739/settings.zip)

**Comment by theyosh** [comment]
Thanks. As I have been fixing other issues today, I will look into this tomorrow...

**Comment by Barbara1984** [comment]
Great thanks for your help

**Comment by theyosh** [comment]
A first look, your setting files is missing a lot of settings. Did you clean it somehow. I am missing
1. admin name
2. language
3. weather url

And I found the problem and solution. You settings file is a bit mangled up. Not sure how that has happened, but I can imagine that my upgrade scripts not always works like expected.

So to fix your switched, edit the settings.cfg file you uploaded here, and go through every switch, and remove the lines:

timer_start = None
timer_stop = None

Every switch has those two lines. After removing them, save the settings.cfg file or upload it. And restart the software. After restart, you are able to add new power switches.

Secondly, I recommend to set the weather location at the system settings page. Because that is now not correct, and not sure what that will cause with my software.

**Comment by Barbara1984** [comment]
Sorry for my late reply but now everything fits with me again. Thanks again
