### ISSUE TITLE
issue in terrariumEnvironment.py

### ISSUE THREAD

**Issue by nke69** [theyosh/TerrariumPI#145]
Hello,

After update, i've got this message ;)

```

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/pi/TerrariumPI/terrariumEnvironment.py", line 681, in __engine_loop
    if self.ph['temperature']['current'] < self.ph['temperature']['alarm_min']:
KeyError: 'temperature'
Fri Apr 27 23:19:54 2018 <Greenlet at 0x6cdc4670: <bound method terrariumEnvironment.__engine_loop of <terrariumEnvironment.terrariumEnvironment object at 0x76bf0570>>> failed with KeyError
```

**Comment by theyosh** [comment]
Ah, found the bug. A new git pull should fix it

**Comment by nke69** [comment]
perfect, no errors after update ;)

**Comment by rrgrow** [comment]
I still get error when updating.. its happened over the last 4-5 updates but I would just reboot and run again but this morning my setup didnt turn lights on and after reboot no TerrariumPI start up. I get:

pi@raspberrypi:~/TerrariumPI $ screen -r
There is no screen to be resumed.
pi@raspberrypi:~/TerrariumPI $ sudo ./start.sh
2018-05-12 14:28:11,000 - INFO - terrariumWrapper - Starting TerrariumPI server running as user 'pi' at location: http://192.168.1.2:8090 ...
pi@raspberrypi:~/TerrariumPI $ screen -r
atch_all
    _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
  File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 167, in _notify_patch
    notify_and_call_entry_points(event)
  File "/usr/local/lib/python2.7/dist-packages/gevent/events.py", line 112, in notify_and_call_entry_points
    subscriber = plugin.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cffi>=1.11.5' distribution was not found and is required by the application
2018-05-12 14:28:15,000 - INFO - terrariumWrapper - Restart counter: 1/5
2018-05-12 14:28:15,000 - INFO - terrariumWrapper - Restarting in 10 seconds after running for 4 seconds. Press Ctrl+C now to terminate TerrariumPI.
10 9 8 7 6 5 4 3 2

and while running install:
 Co9mand "/usr/bi /python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Uvt81E/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-X4YltI-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Uvt81E/cffi/
