### ISSUE TITLE
I meanwhile think that it is not due to my sensors

### ISSUE THREAD

**Issue by vanessa2013** [theyosh/TerrariumPI#52]
Hi Theyosh, I'm 100% sure it's not on my sensors or on my cables. It has to be a hack on the software. Otherwise I can not explain it anymore ... at some point the values (temp. and humidity) are gone.

[Photos.zip](https://github.com/theyosh/TerrariumPI/files/1497499/Photos.zip)

**Comment by theyosh** [comment]
Last picture indicates that the quick fix is to remove the settings.cfg file and restart. This means reconfiguring your setup. If that does not help, more investigation is needed.

I have no time to test it my self. But I do not have problems with 1wire sensors. I have two running for months now.

**Comment by vanessa2013** [comment]
Should I possibly redo the whole rasp?

**Comment by theyosh** [comment]
No. Only make a backup of settings.cfg and remove it from the PI. Then restart. You have to reconfigure the software again. I do not have an explanation why this is happening.

**Comment by vanessa2013** [comment]
Thanks for your tip but unfortunately he brings nothing for me, currently your interface may have some errors otherwise there is not ...

![grafik](https://user-images.githubusercontent.com/31970192/33188540-f2e8b092-d09a-11e7-9929-9c149d6e0c22.png)

![grafik](https://user-images.githubusercontent.com/31970192/33188562-247b42be-d09b-11e7-8b95-5edfaccb6794.png)

**Comment by theyosh** [comment]
Ah, I see.

I am sorry, but I did change the code to use only GPIO numbering. So for your DHT sensor use real GPIO port number which is 40. Enter 40 as new Address. That will also change the ID of the sensor. So after changing it to 40, go to system -> environment and chose the right sensor again and save the new environment setup.

I can a bit confusing right now. But I thought that it would be easier for the consumer to enter either only REAL GPIO port numbers or only BCM. But BCM is than limited, so I chose for REAL GPIO.

My software translate the GPIO portnumbers to right BCM numbers in code.

**Comment by vanessa2013** [comment]
Hi, thanks now everything works fine. Two still ask, it is possible in the future by remote control (Nodemsu 8266) switch. And is it possible at some point to turn off the heating with door sensors when the door is open, so the heater turns off (as with the sprayer).

**Comment by theyosh** [comment]
Ok, nice that it is solved.

Regarding Nodemsu: Nope. I will not make support for external devices directly. There is now an option to add remote sensors through HTTP. So technical it is possible already to support Nodemsu. But you have to program yourself the webserver on the Nodemsu. And that way, the Nodemsu could produce JSON output which can be used with my software. But again, I will not give support on how to develop for a Nodemsu.

About turning off the heater when a door is opened, I suggest to open a new issue. And stick to only 1 problem per issue.

**Comment by vanessa2013** [comment]
Ok, all right, I still have a problem, my DS18B20 sensors always stay at 17 degrees, although it is warmer. It also does not help to empty Chache

**Comment by theyosh** [comment]
Try this answer: https://raspberrypi.stackexchange.com/questions/14978/dallas-1-wire-temperature-sensor-not-working

**Comment by vanessa2013** [comment]
Hi, the problem is not the sensor but where else, as soon as your interface queries the sensors, the sensors disappear under cd / sys / bus / w1 / devices / && ls and there is only w1 bus master present. Did you change something in the code? Only when I start Pi again, all sensors are back, until the interface interrogates again.

**Comment by vanessa2013** [comment]
Unfortunately, this problem is still after the update :-)

**Comment by theyosh** [comment]
Hmmmm, can you try the following:

go to /sys/bus/w1/devices

and enter a folder that starts with '28-'

there enter the following command:

cat w1_slave

What it the outcome of this? An example:

cat w1_slave   
56 01 4b 46 7f ff 0c 10 7b : crc=7b YES  
56 01 4b 46 7f ff 0c 10 7b t=21375

**Comment by vanessa2013** [comment]
Yes I can

![grafik](https://user-images.githubusercontent.com/31970192/33241136-b37f674c-d2c1-11e7-8072-ed61330d2984.png)

**Comment by vanessa2013** [comment]
The interface does not save even if I switch from DHT22 to AM2302, despite empty Chache

**Comment by theyosh** [comment]
Please one issue a time! We are now working on the temperature sensor.

So, please try to remove the DHT22 sensor from the software. So you will only have three temperature sensors left. And then there will be zero humidity sensors.
This is needed to make sure that there is no interference.

So, when the software is running only with DS18B20 sensors try to see what is happening. And then we go further.

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/33241359-6b89724a-d2c4-11e7-9bf8-e77ed83aeaa9.png)

Ok, right now there are no errors with the DS18B20, but my Pi is always offline. Should I make a new ticket for DHT22 now?

**Comment by theyosh** [comment]
No, wait! We will continue on this one for now.

I see an error getting the weather data. Have you updated your weather settings? Or could you check what is you current weather data source?

**Comment by vanessa2013** [comment]
I always use this link:
https://www.yr.no/place/Austria/Vienna/Simmering/

**Comment by theyosh** [comment]
Ok, could you restart your pi? The weather source is working for me.

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/33241545-313126bc-d2c7-11e7-96c0-c5bd607ad1fe.png)

Ok it is currently running, then it may be the DHT22 setting

**Comment by theyosh** [comment]
Ok, so keep this running for let say 10 minutes. To make sure it is working without errors.

Then we close this issue and open a new one for the DHT22 problems. Ok?

**Comment by vanessa2013** [comment]
Ok, thank you very much

**Comment by theyosh** [comment]
No, still wait!. You add new 'problem' again. :)

What is the door name you have entered? Because the first pictures shows an error while saving the door configuration.

**Comment by vanessa2013** [comment]
Upps Sorry, I took the name intermediate door.

**Comment by vanessa2013** [comment]
Zwischentüre

**Comment by vanessa2013** [comment]
Maybe because of the ü

**Comment by theyosh** [comment]
yesh. That is a problem....

**Comment by theyosh** [comment]
Could you try it first using a normal 'u' ?

**Comment by vanessa2013** [comment]
Ok then I will fix that, I have a question for an extension sorry but I have a few ideas to say simply if it bothers: -...

**Comment by theyosh** [comment]
Euh.

Last step for now is adding your DHT sensor. Keep in mind you have to use physical pin numbering. So count it according to https://pinout.xyz

**Comment by vanessa2013** [comment]
Ok what should I select DHT22 or AM2302?

**Comment by vanessa2013** [comment]
I have this: https://electronics.semaf.at/DHT22-Temperature-Humidity-Sensor

**Comment by theyosh** [comment]
Hmmm, that I would not know. Try AM2303 first. If that does not work, change it to DHT22. But make sure you test every time for 2 a 3 minutes. If there are problems it will take some time to show the error.s

**Comment by vanessa2013** [comment]
Ok, I have to restart because so the error under screen -r go away?

**Comment by theyosh** [comment]
which error?

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/33242117-169b1e08-d2d0-11e7-842c-0df39c4807e2.png)

**Comment by vanessa2013** [comment]
If everything fits, but only the first two lines to see

**Comment by theyosh** [comment]
That problem is due to the German language. Could you edit the settings.cfg file and change all the umlauts and other typical German letters to normal letters? That will fix the above problem

**Comment by vanessa2013** [comment]
So "I have to change the German translation completely :-)

**Comment by theyosh** [comment]
No! Only in your settings.cfg file. The translation is just fine

**Comment by vanessa2013** [comment]
Now I have reloaded Putty and get that as a message.
![grafik](https://user-images.githubusercontent.com/31970192/33242255-159b50ac-d2d2-11e7-9c70-0b34d85f8941.png)

**Comment by theyosh** [comment]
above error is because you have on a different putty the software already running. Please reboot

**Comment by vanessa2013** [comment]
Oh yes sorry my mistake, but as I said my setting file is written normally and the errors remain inside.
I have now done a complete reboot now comes this:
![grafik](https://user-images.githubusercontent.com/31970192/33242339-92d0982e-d2d3-11e7-9ebc-1361b17737d4.png)

**Comment by vanessa2013** [comment]
Oh man I hate this fucking DHT22 sensors
![grafik](https://user-images.githubusercontent.com/31970192/33242394-abb0c39a-d2d4-11e7-8c2e-e50a458863a7.png)

**Comment by theyosh** [comment]
Why is you Pi having network problems? Again it cannot retrieve weather data. The second line is the problem. So I have added more code to fix this issue. Please update the code with:

`git pull`

and restart

**Comment by vanessa2013** [comment]
Ok the weather problem is settled, but I have problems with the DHT22 again :-(

![grafik](https://user-images.githubusercontent.com/31970192/33242494-4f1b7cf4-d2d6-11e7-88df-6c92485c904e.png)

**Comment by theyosh** [comment]
What pin number have you entered?

**Comment by vanessa2013** [comment]
![header_pinout](https://user-images.githubusercontent.com/31970192/33242538-e277c20a-d2d6-11e7-87a5-b7d92cb440da.jpg)

**Comment by theyosh** [comment]
Still, the question is. What number have YOU entered?

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/33242552-2a7ceeea-d2d7-11e7-9a7f-27e5288519f2.png)

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/33242571-6919a012-d2d7-11e7-96b4-7b47fccd956d.png)

There are also my sensors gone.

**Comment by theyosh** [comment]
Ok, that is correct.

Then, please remove the DHT sensor here by clicking the small x on the left and add a new one with the type DHT22. Do not just change it in the settings screen. Make sure you have removed the old one and added a new one.

Your temperature sensors are gone due to probably failing DHT sensor... but please ignore for now. The problem is your DHT sensor

**Comment by vanessa2013** [comment]
Ok, even with the setting DHT22 is not since the last update is so

![grafik](https://user-images.githubusercontent.com/31970192/33242631-6ecb4046-d2d8-11e7-9080-aeb2736dfd30.png)

**Comment by vanessa2013** [comment]
Can it be that a 400 volt line disturbs the sensors

**Comment by theyosh** [comment]
Sorry... my fault... will make fix first

**Comment by vanessa2013** [comment]
No problem just let me know, sorry if I'm so annoying

**Comment by theyosh** [comment]
do a `git pull` and restart again. Pleas do not ask multiple questions. Yes, 400 volt power lines will influence your data lines....

But please add just ONE DHT22 sensor to test with. I suggest to use it as a humidity sensor. The more sensors you add... to more complicated it makes. And that is not helping due to the fact I have to ask everytime what you have changed.... This takes to much time. So 1 small step a time please!

**Comment by vanessa2013** [comment]
Ok, after your update it's like this again ...

![grafik](https://user-images.githubusercontent.com/31970192/33242898-f22ab9f0-d2db-11e7-9085-fdaf6ccd42b0.png)

**Comment by vanessa2013** [comment]
Without DHT22 everything fits perfectly

**Comment by theyosh** [comment]
Ok, at this point I think you should able to figure out that a sensor is missing. So update your environment. 

But I stop for tonight. This takes to much time. You know how to test a DHT22 sensor without my software. I have explained that multiple times.

So, for now, I still after days off testing and trying, it is your hardware that is failing. And that I cannot fix. So I conclude that my software is not the problem.

Please do proper testing with your hardware and make sure they work before asking questions.

**Comment by vanessa2013** [comment]
![grafik](https://user-images.githubusercontent.com/31970192/33242936-934f7cf8-d2dc-11e7-8c78-679ea632af84.png)

**Comment by vanessa2013** [comment]
ok

**Comment by javadth** [comment]
good 

[قيمت کرکره برقي](https://xn----zmcbckzcnev7qkavc6a.com/)
